name: CWTools CI

on:
  push:
    branches:    
    - master
    paths:
    - '*/**/*.txt'
    - '*/**/*.yml'
    - '*/**/*.gfx'
    - '*/**/*.gui'
    - 'localisation/**'
    - '!.*/**'
    - '!tutorial/**'
    - '!changelog.txt'
    - '!interface/credits.txt'
  pull_request:
    paths:
    - '*/**/*.txt'
    - '*/**/*.yml'
    - '*/**/*.gfx'
    - '*/**/*.gui'
    - 'localisation/**'
    - '!.*/**'
    - '!tutorial/**'
    - '!changelog.txt'
    - '!interface/credits.txt'

jobs:
  cwtools_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cwtools/cwtools-action@v1.0.0
      with:
        game: hoi4
        cache: 'hoi4.cwb.bz2'
        locLanguages: "english russian"
        suppressedOffenceCategories: '{"failure":[], "warning":["CW242"], "notice":[]}' # suppress empty field warnings
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload output.json
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cwtools_output
        path: output.json
